apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key1
  template:
    metadata:
      labels:
        app: key1
    spec:
      containers:
      - name: container1
        image: najamrizvi3/real_world_jenkins_projb:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: key1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
